export {default as Home} from './Home'
export {default as Crypto} from './Crypto'
export {default as News} from './News'
export {default as Exchange} from './Exchange'
export {default as CoinDetails} from './CoinDetails'